models:
  - name: TGN
    config: config/TGN.yml

datasets:
  - name: LASTFM
    extra_args: "--rand_edge_features 128"

delays:
  - 0
  - 1
  - 2



dim_outs:
  - 128
  - 256

batch_size: 4000
repeats: 3
target_epoch: 100
